- bindings/src/types.rs
Closes:
* https://github.com/elys-network/issues/issues/504
---
I have...
I have...
> feat: implementation of pagination helpers function

- bindings-test/Cargo.toml
- bindings-test/src/lib.rs
- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/Cargo.toml
- bindings/src/lib.rs
- bindings/src/msg_resp.rs
- bindings/src/types.rs
Closes:
* https://github.com/elys-network/issues/issues/493
---
I have...
I have...
> Margin close position mocking

- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/src/querier.rs
- bindings/src/query.rs
- bindings/src/query_resp.rs
- bindings/src/types.rs
Closes:
* https://github.com/elys-network/issues/issues/502
---
I have...
I have...
> Margin query

- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/src/query.rs
- bindings/src/query_resp.rs
- bindings/src/types.rs
Closes:
* https://github.com/elys-network/issues/issues/520
* https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/auth/v1beta1/auth.proto
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, …
> feat: added a binding for the auth module's `Accounts` message

- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/src/msg.rs
- bindings/src/msg_resp.rs
Closes:
* https://github.com/elys-network/issues/issues/522
---
I have...
I have...
> Margin broker msg

- bindings-test/src/multitest.rs
- bindings/src/querier.rs
- bindings/src/query.rs
- bindings/src/query_resp.rs
- bindings/src/types.rs
Closes:
* https://github.com/elys-network/issues/issues/527
---
I have...
I have...
> Implemt SwapEstimationByDenom Query

- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/src/types.rs
some change to make the margin integration easier and fix the mocking of the `OpenMarginBrokerMsg`
> Fix margin

- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/src/msg.rs
- bindings/src/msg_resp.rs
* fix fix/amm_swap_exact_amount_in missing discount argument
> fix: fix amm_swap_exact_amount_in

- Cargo.lock
- bindings-test/Cargo.toml
- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/Cargo.toml
- bindings/src/msg.rs
- bindings/src/msg_resp.rs
- contracts/account-history-contract/Cargo.toml
> feat: delete margin broker message

- bindings/src/msg.rs
- Remove creator item in bindings to follow the latest broker address handling way.
> chore: remove creator

- Cargo.lock
- bindings-test/Cargo.toml
- bindings-test/src/multitest.rs
- bindings/Cargo.toml
- bindings/src/msg.rs
- bindings/src/msg_resp.rs
- bindings/src/types.rs
- contracts/account-history-contract/Cargo.toml
- Add msg binding for AmmJoinPool
- Add msg binding for AmmExitPool
> chore: add join & exit bindings

- Cargo.lock
- bindings-test/Cargo.toml
- bindings-test/src/multitest.rs
- bindings/Cargo.toml
- bindings/src/query_resp.rs
- contracts/account-history-contract/Cargo.toml
- bring withdraw and commit_enabled item back.
> chore: add withdraw and commit_enabled

- Cargo.lock
- bindings-test/Cargo.toml
- bindings-test/src/multitest.rs
- bindings-test/src/tests.rs
- bindings/Cargo.toml
- bindings/src/query_resp.rs
- bindings/src/types.rs
> ci: update the cosmwasm version to have access the `SignedDecimal` type

- contracts/trade-shield-contract/src/action/query/get_margin_position.rs
- contracts/trade-shield-contract/src/action/query/get_margin_positions.rs
- contracts/trade-shield-contract/src/action/query/margin_get_position_for_address.rs
- contracts/trade-shield-contract/src/msg/mod.rs
- contracts/trade-shield-contract/src/msg/query_resp/get_margin_position_resp.rs
- contracts/trade-shield-contract/src/msg/query_resp/get_margin_positions_for_address_resp.rs
- contracts/trade-shield-contract/src/msg/query_resp/get_margin_positions_resp.rs
- contracts/trade-shield-contract/src/types/margin_position_plus.rs
- contracts/trade-shield-contract/src/types/mod.rs
Fields added to the `get position queries` response:
> feat: add position query calculation

- Cargo.lock
- contracts/account-history-contract/Cargo.toml
- contracts/account-history-contract/src/action/query/user_value.rs
- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/account-history-contract/src/entry_point/instantiate.rs
- contracts/account-history-contract/src/msg/instantiate.rs
- contracts/account-history-contract/src/msg/query_resp/user_value_response.rs
- contracts/account-history-contract/src/states/history.rs
- contracts/account-history-contract/src/states/mod.rs
- contracts/account-history-contract/src/states/trade_shield_address.rs
- contracts/account-history-contract/src/tests.rs
- contracts/account-history-contract/src/types/account_snapshot.rs
- contracts/account-history-contract/src/types/mod.rs
- contracts/trade-shield-contract/front_end_script/README.md
- contracts/trade-shield-contract/src/action/query/get_margin_orders.rs
- contracts/trade-shield-contract/src/action/query/get_spot_orders.rs
- contracts/trade-shield-contract/src/msg/query_msg.rs
- contracts/trade-shield-contract/src/msg/query_resp/get_margin_orders_resp.rs
- contracts/trade-shield-contract/src/msg/query_resp/get_spot_orders_resp.rs
- contracts/trade-shield-contract/src/tests/create_spot_order/successful_create_market_order.rs
- contracts/trade-shield-contract/src/tests/get_spot_orders/get_spot_orders.rs
> add the assets and orders assets to the history snapshot

- bindings/src/querier.rs
- bindings/src/query_resp.rs
- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/financial-snapshot-contract/src/bindings/querier.rs
> feat: entry fixed

- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/account-history-contract/src/entry_point/instantiate.rs
- contracts/account-history-contract/src/msg/instantiate.rs
- contracts/account-history-contract/src/types/coin_value.rs
- adding Clone at some point to not loose data
- using oracle `asset_info` query inset of `get_asset_profile` because i noticed that get_asset_profile needed a readable denom and not an ibc/hash
> fix: non stored value

- contracts/account-history-contract/src/action/query/get_staked_assets.rs
- contracts/account-history-contract/src/types/coin_value.rs
1. remove TODO commented code
2. return response even if it is not tracked account.
> chore: minor update

- contracts/financial-snapshot-contract/src/action/query/earn/get_all_validators.rs
Validator USD staked amount is wrong in the Elys staking dropdown. This PR aims to fix that.
> Fix USD staked amount

- .gitignore
- .vscode/settings.json
- bindings/src/account_history/msg/query.rs
- bindings/src/account_history/types/account_snapshot.rs
- bindings/src/account_history/types/mod.rs
- bindings/src/account_history/types/pool_balances.rs
- bindings/src/query_resp.rs
- contracts/account-history-contract/src/action/mod.rs
- contracts/account-history-contract/src/action/query/get_pool_balances.rs
- contracts/account-history-contract/src/action/query/get_pools.rs
- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/account-history-contract/src/entry_point/query.rs
- contracts/account-history-contract/src/states/history.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
- contracts/financial-snapshot-contract/src/action/mod.rs
- contracts/financial-snapshot-contract/src/entry_point/query.rs
- contracts/financial-snapshot-contract/src/msg/query_msg.rs
- scripts/queries.sh
> Account History for Liquidity Pools

- contracts/financial-snapshot-contract/src/action/query/earn/get_all_validators.rs
- contracts/trade-shield-contract/src/action/execute/create_perpetual_order.rs
- contracts/trade-shield-contract/src/tests/create_perpetual_order/change_trigger_price.rs
- contracts/trade-shield-contract/src/tests/mod.rs
> feat: update trigger price of duplicate perpetual close order

- bindings/src/account_history/types/earn_detail/earn_detail.rs
- bindings/src/types.rs
- contracts/account-history-contract/src/tests/get_staked_assets.rs
Profile pictures will be fetched directly from FE plus there is no such profile picture SRC on chain.
> Remove profile picture and add ID to validators

- contracts/trade-shield-contract/src/action/execute/elys_redelegation_request.rs
- contracts/trade-shield-contract/src/action/execute/unstake_request.rs
- contracts/trade-shield-contract/src/tests/mod.rs
- contracts/trade-shield-contract/src/tests/stake_error_handling/eden_cancel_vest_request.rs
- contracts/trade-shield-contract/src/tests/stake_error_handling/eden_vest_request.rs
- contracts/trade-shield-contract/src/tests/stake_error_handling/elys_cancel_unstake_request.rs
- contracts/trade-shield-contract/src/tests/stake_error_handling/elys_redelegation_request.rs
- contracts/trade-shield-contract/src/tests/stake_error_handling/stake_request.rs
- contracts/trade-shield-contract/src/tests/stake_error_handling/unstake_request.rs
*  https://github.com/elys-network/bindings/pull/210
> test: add tests for the the change in the PR #210 and fix messages

- contracts/account-history-contract/src/action/query/get_eden_boost_earn_program_details.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
This is needed to keep consistency in the front.
> Return eden b in base denom

- .vscode/settings.json
- bindings/src/querier.rs
- bindings/src/query_resp.rs
- bindings/src/types.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
- contracts/trade-shield-contract/src/action/execute/open_leveragelp_position_request.rs
https://trello.com/c/XpHBajGR/127-liquidity-mining-revision
> Liquidity mining bindings fix

- bindings-test/src/multitest.rs
- bindings/src/querier.rs
- bindings/src/query_resp.rs
- contracts/trade-shield-contract/src/tests/create_perpetual_order/reproduce_testnet_issue_create_perpetual_market_open_order.rs
changes made to adapt to the changes from this PR:
* https://github.com/elys-network/elys/pull/391
> fix: missing new field in query response:

- bindings/src/trade_shield/types/perpetual_position_plus.rs
- scripts/messages.sh
- scripts/queries.sh
Reverts elys-network/bindings#230
> Revert "Revert "fix: pnl calculation and liquidation price calculation""

- bindings-test/src/multitest.rs
- bindings/src/querier.rs
- bindings/src/query_resp.rs
- contracts/trade-shield-contract/src/tests/create_perpetual_order/reproduce_testnet_issue_create_perpetual_market_open_order.rs
Reverts elys-network/bindings#229
> Revert "Revert "fix: missing new field in query response:""

- bindings/src/query_resp.rs
- contracts/account-history-contract/src/states/history.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
For the dashboard, we need the user's balance on every pool.
> Fix get pools balance

- bindings/src/account_history/types/perpetual_assets.rs
- contracts/account-history-contract/src/states/history.rs
Needed to do stuff w/ current positions..
> Add missing ID to perp endpoint

- bindings/src/account_history/msg/query.rs
- bindings/src/account_history/msg/query_resp/get_all_resp.rs
- bindings/src/account_history/msg/query_resp/user_value_response.rs
- bindings/src/account_history/types/mod.rs
- bindings/src/account_history/types/portfolio_balance_snapshot.rs
- contracts/account-history-contract/src/action/query/all.rs
- contracts/account-history-contract/src/action/query/get_membership_tier.rs
- contracts/account-history-contract/src/action/query/get_portfolio.rs
- contracts/account-history-contract/src/action/query/last_snapshot.rs
- contracts/account-history-contract/src/action/query/user_snapshots.rs
- contracts/account-history-contract/src/action/query/user_value.rs
- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/account-history-contract/src/states/history.rs
- contracts/account-history-contract/src/tests/get_portfolio.rs
- contracts/account-history-contract/src/tests/update_accounts.rs
- contracts/account-history-contract/src/tests/week_snapshots.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
* refactor of the account snapshot to reduce the amount of data stored for each snapshot entry
> refactor: portfolio balance snapshot

- bindings/src/trade_shield/msg/query_resp/get_perpetual_order_resp.rs
- bindings/src/trade_shield/msg/query_resp/get_perpetual_orders_resp.rs
- bindings/src/trade_shield/types/mod.rs
- bindings/src/trade_shield/types/perpetual_order_plus.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
- contracts/trade-shield-contract/src/action/query/get_perpetual_order.rs
- contracts/trade-shield-contract/src/action/query/get_perpetual_orders.rs
- contracts/trade-shield-contract/src/tests/create_perpetual_order/change_trigger_price.rs
- contracts/trade-shield-contract/src/tests/get_perpetual_order/successful_query_message.rs
- contracts/trade-shield-contract/src/tests/process_perpetual_order/pending_limit_open_long_with_price_met.rs
- contracts/trade-shield-contract/src/tests/process_perpetual_order/pending_limit_open_long_with_price_not_met.rs
- contracts/trade-shield-contract/src/tests/process_perpetual_order/pending_limit_open_short_with_price_met.rs
- contracts/trade-shield-contract/src/tests/process_perpetual_order/pending_limit_open_short_with_price_not_met.rs
Perpetual order queries now return a new type called `PerpetualOrderPlus` instead of just the order
```json
{
"order": "PerpetualOrder",
"order_price": "String",
"custody": {
"denom": "String",
"amount": "String"
}
}
```
```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1qg5ega6dykkxc307y25pecuufrjkxkaggkkxh7nad0vhyhtuhw3s7zzmns" '{
"get_perpetual_orders": {
"order_owner": "elys1t8tdmgyk4n92sgj0yt5ds4c8ty36t6vgekp3cf"
}
}'
```
```json
{
"data": {
"page_response": null,
"orders": [
{
"order": {
"order_id": 0,
"owner": "elys1t8tdmgyk4n92sgj0yt5ds4c8ty36t6vgekp3cf",
"order_type": "limit_open",
"position": "long",
"trigger_price": {
"base_denom": "ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65",
"quote_denom": …
```
> feat: custody field and order price

- contracts/trade-shield-contract/src/action/sudo/process_orders.rs
- contracts/trade-shield-contract/src/entry_point/migrate.rs
- remove migrate logic of the last version
- remove double declaration of variable
> perf: remove double declaration of variable

- bindings/src/trade_shield/msg/execute_msg.rs
- bindings/src/trade_shield/msg/mod.rs
- bindings/src/trade_shield/msg/query_msg.rs
- bindings/src/trade_shield/msg/query_resp/params_resp.rs
- bindings/src/trade_shield/states/mod.rs
- bindings/src/trade_shield/states/params.rs
- contracts/trade-shield-contract/src/action/execute/claim_rewards_request.rs
- contracts/trade-shield-contract/src/action/execute/create_perpetual_order.rs
- contracts/trade-shield-contract/src/action/execute/create_spot_order.rs
- contracts/trade-shield-contract/src/action/execute/stake_request.rs
- contracts/trade-shield-contract/src/action/execute/unstake_request.rs
- contracts/trade-shield-contract/src/action/sudo/process_orders.rs
- contracts/trade-shield-contract/src/entry_point/execute.rs
- contracts/trade-shield-contract/src/entry_point/instantiate.rs
- contracts/trade-shield-contract/src/entry_point/migrate.rs
- contracts/trade-shield-contract/src/entry_point/query.rs
- contracts/trade-shield-contract/src/tests/mock/instantiate.rs
```
SetParams {
market_order: Option<bool>,
stake_request: Option<bool>
}
```
```
GetParams {}
```
```
pub struct TradeShieldParamsResponse {
pub market_order: bool,
pub stake_request: bool
}
```
> feat: params endpoint

- bindings/src/account_history/types/coin_value.rs
- bindings/src/account_history/types/portfolio.rs
- bindings/src/account_history/types/total_balance.rs
- contracts/account-history-contract/src/action/query/get_liquid_assets.rs
- contracts/account-history-contract/src/action/query/get_portfolio.rs
- contracts/account-history-contract/src/tests/get_portfolio.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
```sh
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgs98tvuy" '{
"get_total_balance": {
"user_address": "elys1pszy7cq5xhx6dvu082nvyjjd2q6mln9n3k5ly0"
}
}' | jq
```
```json
{
"data": {
"balances": {
"total_balance": "5847921886.9039531186581859",
"portfolio_usd": "5847921886.9039531186581859",
"reward_usd": "0"
}
}
}
```
```sh
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgs98tvuy" '{
"get_portfolio": {
"user_address": "elys1pszy7cq5xhx6dvu082nvyjjd2q6mln9n3k5ly0"
}
}' | jq
```
```json
{
"data": {
"portfolio": {
"balance_usd": "5847921834.47806787201781571",
"liquid_assets_usd": "5119611715.65633128553144071", …
```
> refactor: replace USD value type DecCoin to Decimal256

- bindings/src/types.rs
remaining blocks is returning negative numbers
> Fix eden program

- bindings/src/account_history/types/coin_value.rs
- bindings/src/querier.rs
Fix it once for all. it was approached outside the query itself.
> Fix eden price

- contracts/account-history-contract/src/action/query/exit_pool_estimation.rs
Added fix og my comments of https://github.com/elys-network/bindings/pull/289
> refactor: add a best practices of rust

- bindings/src/account_history/msg/mod.rs
- bindings/src/account_history/msg/query_resp/earn/get_eden_boost_earn_details_resp.rs
- bindings/src/account_history/msg/query_resp/earn/get_eden_earn_details_resp.rs
- bindings/src/account_history/msg/query_resp/earn/get_elys_earn_details_resp.rs
- bindings/src/account_history/msg/query_resp/earn/get_usdc_earn_details_resp.rs
- bindings/src/account_history/msg/query_resp/staked_assets_response.rs
- bindings/src/account_history/types/portfolio.rs
- bindings/src/query_resp.rs
- bindings/src/types.rs
- contracts/account-history-contract/src/action/query/get_staked_assets.rs
- contracts/account-history-contract/src/tests/get_portfolio.rs
- contracts/account-history-contract/src/tests/get_staked_assets.rs
- contracts/account-history-contract/src/tests/update_accounts.rs
- contracts/account-history-contract/src/types/account_snapshot_generator.rs
this task is to include not only staked assets but also unstaking assets, vesting tokens and rewards. We will show the whole amount in the portfolio section with a tooltip that breakdown the different amounts.
https://trello.com/c/JNNwIRU4
> Feat: update get staked assets

- scripts/load_test.sh
add load test script for load testing chain with N accounts and N market buy spot order txs
> test: add load test script

- bindings-test/src/multitest.rs
- bindings/src/account_history/msg/mod.rs
- bindings/src/account_history/msg/query.rs
- bindings/src/account_history/msg/query_resp/masterchef/get_masterchef_stable_stake_response.rs
- bindings/src/querier.rs
- bindings/src/query.rs
- bindings/src/query_resp.rs
- contracts/account-history-contract/src/action/mod.rs
- contracts/account-history-contract/src/action/query/get_masterchef_stable_stake_apr.rs
- contracts/account-history-contract/src/entry_point/query.rs
- scripts/queries.sh
https://trello.com/c/Ky6Te8Kr
Given a coin denom (ueden, uusdc) returns the APR for such coin in the stable stake pool (USDC simple earn)
> feat: masterchef stable stake apr

- scripts/balancer_test.sh
- scripts/messages.sh
test a message script test across all available and enabled nodes in the balancer
```
./scripts/balancer_test.sh stake_request elysvaloper1al6rpllkdgnk3krjs0hxpm9033fpsn5nw69ymf
```
> test: add balancer test script

- bindings/src/account_history/msg/query_resp/get_portfolio_resp.rs
- contracts/account-history-contract/src/action/query/get_portfolio.rs
- contracts/account-history-contract/src/tests/get_portfolio.rs
```rust
pub struct GetPortfolioResp {
pub portfolio: Portfolio,
pub actual_portfolio_balance: SignedDecimal256,
pub old_portfolio_balance: SignedDecimal256,
pub balance_24h_change: SignedDecimal256,
}
```
```rust
pub struct GetPortfolioResp {
pub portfolio: Portfolio,
pub actual_portfolio_balance: SignedDecimal256,
}
```
> feat: 🎸 remove 24h balance changes

- bindings-test/src/multitest.rs
- bindings/src/msg.rs
- bindings/src/query_resp.rs
- bindings/src/trade_shield/msg/execute_msg.rs
- contracts/trade-shield-contract/src/action/execute/claim_rewards_request.rs
- contracts/trade-shield-contract/src/entry_point/execute.rs
- scripts/messages.sh
to test the endpoint use :
```sh
./scripts/messages.sh claim_rewards_request
```
> Claim Reward Request

- bindings/src/types.rs
ValidatorDetail struct was edited to receive the new attrs jailed and inactive
> Filter out jailed validators

- bindings-test/src/multitest.rs
- bindings/src/account_history/msg/query.rs
- bindings/src/querier.rs
- bindings/src/query.rs
- bindings/src/query_resp.rs
- contracts/account-history-contract/src/entry_point/query.rs
- contracts/account-history-contract/src/tests/get_all_pools.rs
- contracts/account-history-contract/src/tests/get_eden_boost_earn_program_details.rs
- contracts/account-history-contract/src/tests/get_eden_earn_program_details.rs
- contracts/account-history-contract/src/tests/get_elys_earn_program_detail.rs
- contracts/account-history-contract/src/tests/get_liquid_assets.rs
- contracts/account-history-contract/src/tests/get_staked_assets.rs
- contracts/account-history-contract/src/tests/get_usdc_earn_program_details.rs
- contracts/account-history-contract/src/tests/update_accounts.rs
- contracts/account-history-contract/src/tests/week_snapshots.rs
Merge this PR if this PR is merged:
* https://github.com/elys-network/elys/pull/512/
> Remove IncentiveAllProgramRewards query

- README.md
- scripts/fast_build.sh
- added a fast-build.sh script to build unoptimized but fast building of contract for localnet deployment and testing.
> feat: add fast build script

- contracts/trade-shield-contract/src/entry_point/migrate.rs
- Testnet upgrade is completed
> Remove migrate logic

- Cargo.lock
- Cargo.toml
- contracts/account-history-contract/Cargo.toml
- contracts/account-history-contract/src/entry_point/instantiate.rs
- contracts/account-history-contract/src/entry_point/migrate.rs
- contracts/financial-snapshot-contract/Cargo.toml
- contracts/financial-snapshot-contract/src/entry_point/instantiate.rs
- contracts/financial-snapshot-contract/src/entry_point/migrate.rs
- contracts/trade-shield-contract/Cargo.toml
- contracts/trade-shield-contract/src/entry_point/instantiate.rs
- contracts/trade-shield-contract/src/entry_point/migrate.rs
- For version control during migration
> Introduce cw2 in contracts

- Cargo.lock
- contracts/account-history-contract/Cargo.toml
- contracts/account-history-contract/src/action/execute/add_user_address_to_queue.rs
- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/account-history-contract/src/entry_point/execute.rs
- contracts/account-history-contract/src/entry_point/migrate.rs
- contracts/account-history-contract/src/entry_point/query.rs
- contracts/account-history-contract/src/states/user_address_queue.rs
- contracts/financial-snapshot-contract/Cargo.toml
- contracts/trade-shield-contract/Cargo.toml
- contracts/trade-shield-contract/src/entry_point/migrate.rs
- update `cw-storage-plus` version
- replace the Vector of address queue by an actual queue
> perf: ⚡️ Use an actual queue instead of loading the vector in up

- bindings/src/account_history/msg/execute.rs
- bindings/src/account_history/msg/query_resp/get_all_resp.rs
- contracts/account-history-contract/src/action/mod.rs
- contracts/account-history-contract/src/action/query/all.rs
- contracts/account-history-contract/src/action/query/last_snapshot.rs
- contracts/account-history-contract/src/action/query/user_snapshots.rs
- contracts/account-history-contract/src/action/sudo/mod.rs
- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/account-history-contract/src/entry_point/execute.rs
- contracts/account-history-contract/src/states/history.rs
- Update `HISTORY` data structure
- Remove HashMap from rust lib
- Add a function to remove data in batches
> Optimize: Update_account

- bindings/src/account_history/msg/execute.rs
- bindings/src/account_history/msg/query_resp/params_resp.rs
- contracts/account-history-contract/src/action/mod.rs
- contracts/account-history-contract/src/action/query/params.rs
- contracts/account-history-contract/src/action/sudo/update_account.rs
- contracts/account-history-contract/src/entry_point/execute.rs
- contracts/account-history-contract/src/entry_point/instantiate.rs
- contracts/account-history-contract/src/entry_point/migrate.rs
- contracts/account-history-contract/src/entry_point/sudo.rs
- contracts/account-history-contract/src/states/history.rs
- contracts/account-history-contract/src/states/mod.rs
- Introduce limit to remove certain number of values
- Add removal for older states
> Introduce limit, add old states removal

- bindings/src/account_history/msg/query_resp/estaking/get_estaking_rewards_response.rs
- bindings/src/query_resp.rs
- contracts/account-history-contract/src/action/query/get_estaking_rewards.rs
As you can see in the screenshots in [this ticket](https://trello.com/c/LBQw5orZ/308-elys-program-rewards-are-delivered-wrongly-to-the-fe) the elys program rewards are being delivered duplicated **per each validator**. So you will see USDC, Eden and Eden Boost rows per each validator you're staking with.
The purpose of this PR is to fix that.
```
{get_elys_earn_program_details: {address: elys1u8c28343vvhwgwhf29w6hlcz73hvq7lwxmrl46}}
```
```
{
"data": {
"bonding_period": 14,
"apr": {
"uusdc": "6154370",
"ueden": "29",
"uedenb": "100"
},
"available": {
"amount": "3225847438",
"usd_amount": "82877.835318790437589351"
},
"staked": {
"usd_amount": "139336.595073846037601234",
"amount": "5007000002",
"lockups": []
},
"rewards": [
{
"denom": …
```
> Fix Elys staking rewards

- bindings-test/src/multitest.rs
- bindings/src/account_history/msg/query.rs
- bindings/src/querier.rs
- bindings/src/query.rs
- bindings/src/query_resp.rs
- bindings/src/trade_shield/msg/query_msg.rs
- contracts/account-history-contract/src/entry_point/query.rs
- contracts/trade-shield-contract/src/entry_point/query.rs
- scripts/queries.sh
> new Leveragelp Query

- bindings-test/src/multitest.rs
- bindings/src/msg.rs
- bindings/src/trade_shield/msg/execute_msg.rs
- contracts/trade-shield-contract/src/action/execute/update_stop_loss_leverage.rs
- contracts/trade-shield-contract/src/action/mod.rs
- contracts/trade-shield-contract/src/entry_point/execute.rs
- Add endpoints for update_stop_loss message
> Leveragelp: Stop loss message

- README.md
Re-apply PR https://github.com/elys-network/bindings/pull/381
> docs: improved testnet snapshot intructions

- .github/workflows/pipeline.yml
version was changed for commit
> version was changed for commit

- bindings/src/query_resp.rs
- contracts/trade-shield-contract/src/helper.rs
- fix swap error
- Discount value was not properly converted
> Swap error fix
